import { Category, Product } from "./types";

export const categories: Category[] = [
  {
    id: "alarmes-intrusao",
    name: "Alarmes de intrusão",
    shortName: "Intrusão",
    description: "Centrais, detetores, teclados e acessórios para proteção total.",
    icon: "shield",
    count: 148,
    subcategories: ["Centrais de alarme", "Detetores com e sem fio", "Teclados", "Comunicadores", "Sirenes", "Kits de alarme"],
  },
  {
    id: "alarmes-incendio",
    name: "Alarmes de incêndio",
    shortName: "Incêndio",
    description: "Deteção, alerta e sinalética para instalações seguras.",
    icon: "flame",
    count: 61,
    subcategories: ["Centrais de incêndio", "Detetores", "Botoneiras", "Sirenes", "Cabos", "Sinalética"],
  },
  {
    id: "cctv",
    name: "Videovigilância CCTV",
    shortName: "CCTV",
    description: "Câmaras IP, gravadores, monitores e soluções profissionais.",
    icon: "camera",
    count: 204,
    subcategories: ["Câmaras IP", "Dome", "Tubulares", "Gravadores DVR / NVR", "Kits CCTV", "Acessórios CCTV"],
  },
  {
    id: "baterias-fontes",
    name: "Baterias e alimentação",
    shortName: "Energia",
    description: "Fontes, baterias, pilhas e alimentação PoE.",
    icon: "battery",
    count: 73,
    subcategories: ["Alimentação PoE", "Baterias", "Fontes 12V", "Fontes 24V", "Fontes 5V", "Pilhas"],
  },
  {
    id: "acessos-fibra",
    name: "Acessos e fibra ótica",
    shortName: "Acessos & fibra",
    description: "Controlo de acessos, fibra e infraestrutura de rede.",
    icon: "scan",
    count: 92,
    subcategories: ["Controlo de acessos", "Cabos de fibra", "Média converters", "Patchcords", "Máquinas de fusão"],
  },
  {
    id: "comandos-recetores",
    name: "Comandos e recetores",
    shortName: "Comandos",
    description: "Automação residencial, portões e interruptores inteligentes.",
    icon: "radio",
    count: 39,
    subcategories: ["Comandos 433 MHz", "Recetores", "SmartSwitch", "Automação residencial"],
  },
  {
    id: "componentes-medicao",
    name: "Componentes e medição",
    shortName: "Componentes",
    description: "Instrumentação, módulos de relé, sensores e componentes técnicos.",
    icon: "tool",
    count: 42,
    subcategories: ["Multímetros", "Pinças amperimétricas", "Módulos de relé", "Sensores de humidade", "Outros componentes"],
  },
  {
    id: "reparacoes",
    name: "Reparações",
    shortName: "Reparações",
    description: "Diagnóstico e assistência a equipamentos de segurança eletrónica.",
    icon: "tool",
    count: 8,
    subcategories: ["Diagnóstico", "Reparação de centrais", "Assistência técnica"],
  },
];

const image = (id: number) => `/products/${id}.jpg`;

const common = {
  vatRate: 0.23,
  rating: 4.8,
  reviews: 12,
};

export const products: Product[] = [
  {
    ...common,
    id: 785,
    slug: "interruptor-inteligente-mini-smartswitch",
    name: "Interruptor Inteligente Compacto para Automação Residencial — MiniSmartSwitch",
    shortName: "MiniSmartSwitch Wi-Fi",
    reference: "MINISMARTSWITCH",
    brand: "Kingates",
    category: "comandos-recetores",
    subcategory: "SmartSwitch",
    price: 12.25,
    stock: "available",
    stockLabel: "Disponível",
    image: image(785),
    gallery: [image(785)],
    badge: "Mais vendido",
    featured: true,
    isNew: true,
    description: "Interruptor Wi-Fi compacto para controlar iluminação e pequenos equipamentos através do telemóvel.",
    features: ["Controlo remoto por Wi-Fi", "Formato compacto", "Instalação simples", "Compatível com automação residencial"],
    specs: { Alimentação: "100–240 V AC", Corrente: "10 A máx.", Rede: "Wi-Fi 2.4 GHz", Aplicação: "iOS e Android" },
  },
  {
    ...common,
    id: 690,
    slug: "central-alarme-paradox-sp4000",
    name: "Central de Alarme de Intrusão por Cabo Paradox SP4000",
    shortName: "Central Paradox SP4000",
    reference: "SP4000",
    brand: "Paradox",
    category: "alarmes-intrusao",
    subcategory: "Centrais de alarme",
    price: 58,
    oldPrice: 64.9,
    stock: "available",
    stockLabel: "Disponível",
    image: image(690),
    gallery: [image(690)],
    badge: "-11%",
    featured: true,
    description: "Central de 4 zonas expansível até 32 zonas, concebida para instalações residenciais e comerciais.",
    features: ["4 zonas na placa", "Expansível a 32 zonas", "Até 32 utilizadores", "Compatível com módulos Paradox"],
    specs: { Zonas: "4 a 32", Utilizadores: "32", Partições: "2", Certificação: "CE" },
  },
  {
    ...common,
    id: 72,
    slug: "detetor-paradox-pmd75-868mhz",
    name: "Detetor Volumétrico sem Fio Paradox 868 MHz Imune a Animais — PMD75",
    shortName: "Detetor Paradox PMD75",
    reference: "PMD75-868",
    brand: "Paradox",
    category: "alarmes-intrusao",
    subcategory: "Detetores sem fio",
    price: 59.5,
    stock: "available",
    stockLabel: "Disponível",
    image: image(72),
    gallery: [image(72)],
    featured: true,
    description: "Detetor via rádio de dupla ótica, imune a animais até 40 kg e indicado para espaços interiores.",
    features: ["Frequência 868 MHz", "Imunidade a animais até 40 kg", "Dupla ótica", "Compensação de temperatura"],
    specs: { Alcance: "11 × 11 m", Frequência: "868 MHz", Altura: "2,0–2,7 m", Bateria: "3 × AAA" },
  },
  {
    ...common,
    id: 805,
    slug: "emissor-recetor-ethernet-ip-coaxial-et-ip-v",
    name: "Emissor / Recetor Ethernet IP por Cabo Coaxial — ET-IP-V",
    shortName: "Extensor Ethernet ET-IP-V",
    reference: "ET-IP-V",
    brand: "Jolarme",
    category: "acessos-fibra",
    subcategory: "Conversores de rede",
    price: 72,
    stock: "available",
    stockLabel: "Disponível",
    image: image(805),
    gallery: [image(805)],
    featured: true,
    isNew: true,
    description: "Transmissão de Ethernet sobre cabo coaxial existente, ideal para modernizar instalações CCTV sem recablagem.",
    features: ["Porta Ethernet 10/100Base-TX", "Transmissão por cabo coaxial", "Até 6 unidades na mesma linha", "Instalação plug-and-play"],
    specs: { Ethernet: "10/100 Mbps", Conector: "RJ-45 + BNC", Distância: "Até 400 m", Alimentação: "12 V DC" },
  },
  {
    ...common,
    id: 750,
    slug: "camara-tubular-ip-safire-4mp",
    name: "Câmara Tubular IP Safire 4MP PoE IR 30 m IP67",
    shortName: "Câmara Safire 4MP",
    reference: "SF-IPB035WH-4P-0600",
    brand: "Safire",
    category: "cctv",
    subcategory: "Câmaras IP",
    price: 75,
    oldPrice: 89,
    stock: "available",
    stockLabel: "Disponível",
    image: image(750),
    gallery: [image(750)],
    badge: "Oferta",
    featured: true,
    description: "Câmara IP exterior de 4 MP com visão noturna, PoE e corpo resistente às condições meteorológicas.",
    features: ["Resolução 4 MP", "Lente fixa 6 mm", "Infravermelhos 30 m", "PoE e proteção IP67"],
    specs: { Resolução: "4 MP", Lente: "6 mm", Infravermelhos: "30 m", Proteção: "IP67" },
  },
  {
    ...common,
    id: 777,
    slug: "botao-sos-wifi-idosos-cf100",
    name: "SOS Wi-Fi para Idosos — Botão de Emergência CF100",
    shortName: "Botão SOS Wi-Fi CF100",
    reference: "CF100",
    brand: "CareHome",
    category: "alarmes-intrusao",
    subcategory: "Botões de pânico",
    price: 75,
    stock: "available",
    stockLabel: "Disponível",
    image: image(777),
    gallery: [image(777)],
    featured: true,
    isNew: true,
    description: "Botão de emergência Wi-Fi com alarme sonoro e notificações para apoio rápido a pessoas idosas.",
    features: ["Alertas no telemóvel", "Alarme sonoro", "Botão de grandes dimensões", "Configuração Wi-Fi"],
    specs: { Rede: "Wi-Fi 2.4 GHz", Alimentação: "5 V DC", Sirene: "Integrada", Aplicação: "iOS e Android" },
  },
  {
    ...common,
    id: 77,
    slug: "detetor-bosch-tritech-blue-line",
    name: "Detetor de Dupla Tecnologia TriTech Bosch Blue Line Gen2",
    shortName: "Detetor Bosch TriTech",
    reference: "ISC-BDL2-W12G",
    brand: "Bosch",
    category: "alarmes-intrusao",
    subcategory: "Detetores com fio",
    price: 89,
    stock: "available",
    stockLabel: "Disponível",
    image: image(77),
    gallery: [image(77)],
    featured: true,
    description: "Detetor profissional que combina infravermelhos e micro-ondas para reduzir falsos alarmes.",
    features: ["Tecnologia TriTech", "Cobertura de 12 m", "Compensação dinâmica", "Ótica selada"],
    specs: { Cobertura: "12 × 12 m", Tecnologia: "PIR + micro-ondas", Montagem: "2,2–2,75 m", Cor: "Branco" },
  },
  {
    ...common,
    id: 795,
    slug: "nvr-hikvision-4-canais-8mp",
    name: "Videogravador IP Hikvision 4 Canais até 8MP",
    shortName: "NVR Hikvision 4 canais",
    reference: "HWN-4104MH-4P",
    brand: "Hikvision",
    category: "cctv",
    subcategory: "Gravadores NVR",
    price: 121,
    stock: "available",
    stockLabel: "Disponível",
    image: image(795),
    gallery: [image(795)],
    badge: "Profissional",
    featured: true,
    description: "NVR compacto com quatro portas PoE e gravação até 8 MP para instalações de videovigilância profissionais.",
    features: ["4 canais IP", "4 portas PoE", "Gravação até 8 MP", "Acesso remoto"],
    specs: { Canais: "4", Resolução: "Até 8 MP", PoE: "4 portas", Disco: "1 × SATA" },
  },
  {
    ...common,
    id: 751,
    slug: "camara-dome-ip-safire-4mp-varifocal",
    name: "Câmara Dome IP Safire 4MP Varifocal PoE IR 30 m",
    shortName: "Dome Safire 4MP",
    reference: "SF-IPT855ZWA-4E",
    brand: "Safire",
    category: "cctv",
    subcategory: "Câmaras dome",
    price: 130,
    stock: "available",
    stockLabel: "Disponível",
    image: image(751),
    gallery: [image(751)],
    featured: true,
    description: "Câmara dome varifocal para exterior, com imagem de alta definição e alimentação PoE.",
    features: ["Resolução 4 MP", "Lente 2.8–12 mm", "IR até 30 m", "PoE e IP67"],
    specs: { Resolução: "4 MP", Lente: "2.8–12 mm", Infravermelhos: "30 m", Proteção: "IP67" },
  },
  {
    ...common,
    id: 405,
    slug: "teclado-touch-paradox-tm70",
    name: "Teclado Touch Paradox de 7 polegadas Branco — TM70",
    shortName: "Teclado Paradox TM70",
    reference: "TM70",
    brand: "Paradox",
    category: "alarmes-intrusao",
    subcategory: "Teclados",
    price: 165,
    stock: "limited",
    stockLabel: "Disponível em 2–3 dias",
    image: image(405),
    gallery: [image(405)],
    description: "Teclado tátil a cores para controlo intuitivo de sistemas de alarme Paradox.",
    features: ["Ecrã tátil de 7 polegadas", "Interface personalizável", "Leitor microSD", "Compatível com centrais Paradox"],
    specs: { Ecrã: "7” capacitivo", Resolução: "800 × 480", Cor: "Branco", Ligação: "BUS Paradox" },
  },
  {
    ...common,
    id: 717,
    slug: "central-inim-smartliving-sml1050-g3",
    name: "Central de Alarme INIM SmartLiving 10–50 Zonas Grau 3",
    shortName: "Central INIM SML1050/G3",
    reference: "SML1050/G3",
    brand: "INIM",
    category: "alarmes-intrusao",
    subcategory: "Centrais de alarme",
    price: 247,
    stock: "available",
    stockLabel: "Disponível",
    image: image(717),
    gallery: [image(717)],
    featured: true,
    description: "Central híbrida certificada Grau 3, flexível para instalações de média dimensão com e sem fios.",
    features: ["10 a 50 zonas", "Tecnologia híbrida", "Certificação Grau 3", "Gestão remota"],
    specs: { Zonas: "10 a 50", Grau: "3", Partições: "10", Tecnologia: "Cabo + sem fios" },
  },
  {
    ...common,
    id: 583,
    slug: "kit-video-porteiro-ip-hikvision",
    name: "Kit Vídeo Porteiro IP Hikvision — DS-KIS602",
    shortName: "Kit Vídeo Porteiro Hikvision",
    reference: "DS-KIS602",
    brand: "Hikvision",
    category: "acessos-fibra",
    subcategory: "Vídeo porteiros",
    price: 477,
    stock: "limited",
    stockLabel: "Disponível em 2–3 dias",
    image: image(583),
    gallery: [image(583)],
    badge: "Kit completo",
    featured: true,
    description: "Kit IP completo com monitor interior e videoporteiro para comunicação e abertura remota.",
    features: ["Monitor interior tátil", "Câmara HD", "Abertura remota", "Ligação IP"],
    specs: { Monitor: "7 polegadas", Câmara: "HD", Ligação: "Ethernet", Alimentação: "PoE" },
  },
  {
    ...common,
    id: 64,
    slug: "teclado-lcd-paradox-k32lcd",
    name: "Teclado por Cabo LCD Paradox — K32LCD+",
    shortName: "Teclado Paradox K32LCD+",
    reference: "K32LCD+",
    brand: "Paradox",
    category: "alarmes-intrusao",
    subcategory: "Teclados",
    price: 89.9,
    stock: "unavailable",
    stockLabel: "Indisponível",
    image: image(64),
    gallery: [image(64)],
    description: "Teclado LCD alfanumérico para sistemas Paradox, com interface clara e teclas dedicadas.",
    features: ["Ecrã LCD", "32 zonas", "Teclas de pânico", "Retroiluminação"],
    specs: { Zonas: "32", Ecrã: "LCD", Cor: "Branco", Ligação: "BUS Paradox" },
  },
  {
    ...common,
    id: 107,
    slug: "modulo-expansor-incendio-inim-smartline",
    name: "Módulo Expansor de 8 Zonas para Central de Incêndio INIM SmartLine",
    shortName: "Expansor INIM SmartLine 8Z",
    reference: "SMARTLINE/8Z",
    brand: "INIM",
    category: "alarmes-incendio",
    subcategory: "Centrais de incêndio",
    price: 85,
    stock: "available",
    stockLabel: "Disponível",
    image: image(107),
    gallery: [image(107)],
    description: "Módulo de expansão de oito zonas para centrais convencionais INIM SmartLine.",
    features: ["8 zonas adicionais", "Integração SmartLine", "Instalação em caixa", "Configuração simples"],
    specs: { Zonas: "8", Compatibilidade: "SmartLine 020-4", Montagem: "Interior", Marca: "INIM" },
  },
  {
    ...common,
    id: 389,
    slug: "central-incendio-teletek-mag4p",
    name: "Central de Incêndio Convencional 4 Zonas Teletek MAG4P",
    shortName: "Central Teletek MAG4P",
    reference: "MAG4P",
    brand: "Teletek",
    category: "alarmes-incendio",
    subcategory: "Centrais de incêndio",
    price: 128,
    stock: "limited",
    stockLabel: "Disponível em 2–3 dias",
    image: image(389),
    gallery: [image(389)],
    description: "Central convencional de quatro zonas em caixa plástica para pequenos e médios projetos.",
    features: ["4 zonas convencionais", "Indicação LED", "Saídas de sirene", "Caixa compacta"],
    specs: { Zonas: "4", Tipo: "Convencional", Caixa: "Plástica", Marca: "Teletek" },
  },
  {
    ...common,
    id: 687,
    slug: "bateria-6v-1-2ah",
    name: "Bateria Selada 6V 1,2Ah — OP1,2-6",
    shortName: "Bateria 6V 1,2Ah",
    reference: "OP1,2-6",
    brand: "Optimus",
    category: "baterias-fontes",
    subcategory: "Baterias",
    price: 10.8,
    stock: "available",
    stockLabel: "Disponível",
    image: image(687),
    gallery: [image(687)],
    description: "Bateria de chumbo selada para equipamentos de segurança e alimentação de emergência.",
    features: ["6 V", "Capacidade 1,2 Ah", "Sem manutenção", "Uso em standby"],
    specs: { Tensão: "6 V", Capacidade: "1,2 Ah", Tecnologia: "Chumbo selado", Manutenção: "Não requerida" },
  },
  {
    ...common,
    id: 534,
    slug: "multimetro-bolso-digital-unit-ut33d",
    name: "Multímetro de Bolso Digital com NCV UNI-T — UT-33D+",
    shortName: "Multímetro UNI-T UT-33D+",
    reference: "UT-33D+",
    brand: "UNI-T",
    category: "componentes-medicao",
    subcategory: "Multímetros",
    price: 23.25,
    stock: "available",
    stockLabel: "Disponível",
    image: image(534),
    gallery: [image(534)],
    isNew: true,
    description: "Multímetro digital compacto com deteção de tensão sem contacto para trabalho técnico diário.",
    features: ["Deteção NCV", "Ecrã digital", "Formato de bolso", "Proteção contra sobrecarga"],
    specs: { Display: "LCD", NCV: "Sim", Alimentação: "2 × AAA", Marca: "UNI-T" },
  },
];

export const brands = [...new Set(products.map((product) => product.brand))].sort();

export function getProduct(identifier: string | number) {
  return products.find((product) => product.id === Number(identifier) || product.slug === identifier);
}

export function formatPrice(value: number) {
  return new Intl.NumberFormat("pt-PT", { style: "currency", currency: "EUR" }).format(value);
}
